---
- name: Update the servers 
  hosts: all 
  gather_facts: no
  become: yes
  tasks: 
    - name: Update apt package 
      ansible.builtin.apt:
        update_cache: yes 
        upgrade: dist 
      register: update_output
  
    - name: Display update output 
      debug: 
        var: update_output.stdout

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present 
      register: docker_result

    - name: Display Docker installtion output 
      debug: 
        var: docker_result.stdout